### ISSUE TITLE
kfp-csi-s3 installation on RedHat OpenShift on AWS (ROSA) fails

### ISSUE THREAD

**Issue by maxdebayser** [IBM/manifests#42]
I'm not sure if OpenShift in general is in scope for this fork, but I'll open this issue at least for future reference.

In ROSA the kubelet path is `/var/lib/kubelet` while both in ROKS and IKS it is `/var/data/kubelet`. When deployed as is, the `kfp-csi-s3` DaemonSet fails to initialize. The solution is to replace all paths in that DaemonSet, in the `csi-attacher-s3` StatefulSet and the `csi-provisioner-s3` Statefulset. After that the volumes are provisioned correctly and can be attached to pods.

If that's something that would make sense for this fork, I can open a PR with a kustomization to changes the paths for ROSA.

**Comment by maxdebayser** [comment]
Sorry for taking so long. The changes in `kind` do seem correct. However, the installation of kfp-csi-s3 that I'm using is located in `apps/kfp-tekton/upstream/third-party/kfp-csi-s3/csi-s3-deployment.yaml` and is included by the `iks-multi` kustomization. I'm not sure if I can just replace one with another.

**Comment by ckadner** [comment]
> @ckadner , this kustomize patch fixes the deployment manifests for me:
> 
> ```
> patchesJson6902:
> - target:
>     version: v1
>     kind: DaemonSet
>     name: kfp-csi-s3
>   patch: |-
>     - op: replace
>       path: /spec/template/spec/containers/0/args/2
>       value: "--kubelet-registration-path=/var/lib/kubelet/plugins/kfp-csi-s3/csi.sock"
>     - op: replace
>       path: /spec/template/spec/containers/1/volumeMounts/1/mountPath
>       value: /var/lib/kubelet/pods
>     - op: replace
>       path: /spec/template/spec/volumes/0/hostPath/path
>       value: /var/lib/kubelet/plugins/kfp-csi-s3
>     - op: replace
>       path: /spec/template/spec/volumes/1/hostPath/path
>       value: /var/lib/kubelet/pods
>     - op: replace
>       path: /spec/template/spec/volumes/2/hostPath/path
>       value: /var/lib/kubelet/plugins_registry
> - target:
>     version: v1
>     kind: StatefulSet
>     name: csi-attacher-s3
>   patch: |-
>     - op: replace
>       path: /spec/template/spec/volumes/0/hostPath/path
>       value: /var/lib/kubelet/plugins/kfp-csi-s3
> - target:
>     version: v1
>     kind: StatefulSet
>     name: csi-provisioner-s3
>   patch: |-
>     - op: replace
>       path: /spec/template/spec/volumes/0/hostPath/path
>       value: /var/lib/kubelet/plugins/kfp-csi-s3
> ```

Thank you @maxdebayser -- I had temporarily changed all the paths in `apps/kfp-tekton/upstream/third-party/kfp-csi-s3/csi-s3-deployment.yaml` to get it running before I saw your issue but I wanted to record some of the error messages for future reference.
